apiVersion: v2
name: one37id-bcagent
type: application
description: A Kubernetes Helm chart for the One37 Business Connector Agent
home: https://one37id.com
icon: https://www.one37id.com/images/connector.svg
annotations:
  category: Infrastructure
  licenses: Apache-2.0
dependencies:
  - name: one37secrets
    repository: https://fedoraman137.github.io/helm-test/one37secrets
    tags:
    - one37secrets
    version: 0.1.x
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
    - postgresql
    version: 12.x.x
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
    - redis
    version: 18.x.x
keywords:
  - businessconnector
  - ssi
  - aries
  - agent
  - one37id
  - one37
  - one37id.com
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "1.1.2308.1802"
version: 1.2309.0804
