apiVersion: v2
name: one37id-bcagent
description: A Kubernetes Helm chart for the One37 Business Connector Agent
annotations:
  category: Infrastructure
  licenses: Apache-2.0
type: application
home: https://one37id.com
icon: https://www.one37id.com/images/connector.svg
keywords:
  - businessconnector
  - ssi
  - aries
  - agent
  - one37id
  - one37
  - one37id.com
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "1.2306.0701"
version: 1.2306.0
