annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
type: application
name: one37id-mediator
description: The One37id Mediator is a component that acts as a store/forward inbox between the Aries v1 Agents and the One37id Upa! Wallet. It is responsible for notifying and holding messages for each connected wallet.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - phpmyadmin
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "1.2306.3001"
version: 0.1.0