apiVersion: v1
data:
  tls.crt: >-
    {{ .Values.tls.crt }}
  tls.key: >-
    {{ .Values.tls.key }}
kind: Secret
metadata:
  annotations: {}
  name: {{ include "one37id-tls-dev.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: kubernetes.io/tls
