apiVersion: v1
data:
  tls.crt: >-
    {{ .Values.tls.crt }}
  tls.key: >-
    {{ .Values.tls.key }}
kind: Secret
metadata:
  annotations: {}
  name: {{ include "one37secrets.fullname" . }}-tls
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: kubernetes.io/tls
