apiVersion: v1
kind: Service
metadata:
  name: {{ include "one37id-bcagent.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "one37id-bcagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.publicport }}
      targetPort: {{ .Values.service.publicport }}
      protocol: TCP
      name: http-public
    - port: {{ .Values.service.adminport }}
      targetPort: {{ .Values.service.adminport }}
      protocol: TCP
      name: http-admin
  selector:
    {{- include "one37id-bcagent.selectorLabels" . | nindent 4 }}
