{{- $fullName := include "one37id-bcagent-oc.fullname" . -}}
{{- $svcPort := .Values.service.publicPort -}}
{{- $svcAdminPort := .Values.service.adminPort -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
# {{- if .Values.service.twoPortMode }}
#   KESTREL_PORT: {{ $svcAdminPort | quote }}
#   STANDALONE_PORT: {{ $svcPort | quote }}
# {{- else }}
#   KESTREL_PORT: {{ $svcPort | quote }}
# {{- end }}
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}