{{- $fullName := include "one37id-ibm-agent.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  REDIS_HOST: {{ .Values.redisName }}-master
  REDIS_PORT: 6379
  PG_HOST: {{ .Values.postgresName }}
  PG_PORT: 5432
  PG_CONNECTION: {{ .Values.postgresName }}:5432
  PG_DBNAME: {{ $fullName }}_agent_db
  WALLET_PG_DBNAME: {{ $fullName }}_wallet_db
  WORKFLOW_PG_DBNAME: {{ $fullName }}_workflow_db
  AUDIT_PG_DBNAME: {{ $fullName }}_audit_db
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}