{{- $fullName := include "one37id-ibm-agent.fullname" . -}}
{{- $pgPort := "5432" -}}
{{- $pgConnection := printf "%s:%s" .Values.postgresName $pgPort -}}
{{- $redisHost := printf "%s-%s" .Values.redisName "master" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  REDIS_HOST: {{ $redisHost | quote }}
  REDIS_PORT: "6379"
  PG_HOST: {{ .Values.postgresName | quote }}
  PG_PORT: "5432"
  PG_CONNECTION: {{ $pgConnection | quote }}
  PG_DBNAME: {{ $fullName }}_agent_db
  WALLET_PG_DBNAME: {{ $fullName }}_wallet_db
  WORKFLOW_PG_DBNAME: {{ $fullName }}_workflow_db
  AUDIT_PG_DBNAME: {{ $fullName }}_audit_db
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}