{{- $fullName := include "one37id-ibm-agent.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName}}-{{ .Values.volume.name }}
spec:
  accessModes:
{{ toYaml .Values.volume.accessModes | indent 4 }}
  storageClassName: {{ .Values.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}

