apiVersion: v1
kind: Service
metadata:
  name: {{ include "one37id-ibm-agent.fullname" . }}
  labels:
    {{- include "one37id-ibm-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - port: {{ $value }}
      targetPort: {{ $value }}
      protocol: TCP
      name: {{ $key}}
    {{- end }}
  selector:
    {{- include "one37id-ibm-agent.selectorLabels" . | nindent 4 }}
