annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
type: application
name: one37id-env
description: The One37id Platform support for deployment of the One37id workloads and services.
home: https://one37id.com
icon: https://www.one37id.com/favicon.ico
keywords:
  - One37id
  - decentralised trust
  - identity
  - identity management
  - identity verification
  - identity wallet
  - identity credentials
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "1.2307.2401"
version: 1.2307.3