# Default values for one37-mediator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: true
  name: one37

image:
  # Specifies whether to create a secret for pulling images from a registry.
  createSecret: true
  # Secret name to be used for pulling images from a registry.
  secretName: gitlab-auth
