{{- if .Values.image.createSecret }}
{{- $user := .Values.image.user }}
{{- $pass := .Values.image.password }}
{{- $authraw := printf "%s:%s" $user $pass -}}
{{- $auth := $authraw | b64enc | quote }}
{{- $configRaw := printf "{\"auths\": {\"registry.gitlab.com\": {\"auth\": %s }}}" $auth -}}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.image.secretName }}
  namespace: {{ .Values.namespace.name }}
data:
  .dockerconfigjson: {{ $configRaw | b64enc }}
type: kubernetes.io/dockerconfigjson
{{- end }}
