{{- if .Values.image.createSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.image.secretName }}
  namespace: {{ .Values.namespace.name }}
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6IHsicmVnaXN0cnkuZ2l0bGFiLmNvbSI6IHsiYXV0aCI6ICJiMjVsTXpjdGNtVmhaRHBwZW00NVFqTktRV2hRWjJkb1RHczNhVVI2TlE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
{{- end }}