{{- if .Values.workflowVolume.enabled }}
{{- $fullName := include "one37id-bcagent2.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workflowVolume.name }}
spec:
  accessModes:
{{ toYaml .Values.workflowVolume.accessModes | indent 4 }}
  storageClassName: {{ .Values.workflowVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.workflowVolume.size }}
{{- end -}}
