# Default values for one37 Business Connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullname: ""

# Enable this if you want have liveness and readiness probes
liveCheck: false


# Any value here above 1 will require the REDIS or MQ service
# to be enabled and specified below
replicaCount: 1

# The Business Connector can host the public and admin API on the different ports if needed
service:
  type: "ClusterIP"
  twoPortMode: false
  publicPort: "8080"
  adminPort:  "8080"

ingress:
  enabled: false
  # className: nginx # use this for Azure with open source nginx ingress controller
  className: ""  # use this for IBM Cloud
  annotations:
    kubernetes.io/ingress.class: public-iks-k8s-nginx  # Only use this for IBM Cloud
    proxybodysize: "50m"
  hosts:
    - host: ibmtest2.dev-one37.id
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              port:
                number: 8080
        #if you want to add another path for admin
        # - path: /config
        #   pathType: ImplementationSpecific
        #   backend:
        #     service:
        #       port:
        #         number: 8081
  tls:
    - secretname: one37secrets-tls
      hosts:
        - ibmtest2.dev-one37.id


configmap:
  ASPNETCORE_ENVIRONMENT: "Development"
  MINIMUM_LOG_LEVEL: 1
  AGENT_ALIAS: "ibmtest"

environment:
  AGENT_SETUP_MODE: "true"
  USE_HTTPS_MESSAGE_TYPES: "false"
  USE_HTTPS: "false"
  IS_RUNNING_BEHIND_PROXY: "true"
  SSO_ENABLED: "false"
  AGENT_CATEGORY: "Business"
  ARS_URL: https://ars.dev-one37.id
  ARS_ALIAS: "ars"
  AGENT_GENESIS: https://raw.githubusercontent.com/One37ID/indy-did-networks/one37/networks/one37id/testnet/pool_transactions_genesis
  AGENT_POOL: "one37id-devnet"
  ARS_ENDPOINT: https://ars-agent.dev-one37.id/agent
  USE_STUDIO_CONFIG: "true"
  STUDIO_URL: https://studio.dev-one37.id
  CONFIGURATION_URL: https://studio.dev-one37.id
  # CREDENTIAL_CLEANER_SERVICE_CRON: "*/5 * * * *"
  # WORKFLOW_CLEANER_SERVICE_CRON: "*/1 * * * *"
    #Metrics Support
  OTEL_METRICS_ENABLED: "false"
  OTEL_LOGGING_ENABLED: "false"
  OTEL_PROMETHEUS_EXPORT: "false"
  OTEL_ENDPOINT: "https://simplist-collector:4317"
  OTEL_PROTOCOL: "GRPC"

  PG_HOST: "one37-psql"
  PG_PORT: "5432"
  PG_CONNECTION: "one37-psql:5432"
  REDIS_HOST: "one37-redis-master"
  REDIS_PORT: "6379"

secrets:
  create: true
  postgresSecretName: "one37-psql"
  redisSecretName: "one37-redis"
  app:
    PG_USER: postgres
    PG_ADMIN_USER: postgres
    WALLET_KEY: ""
    AGENT_NYM: ""
    STUDIO_CONTACT_ID: ""
    CONFIGURATION_SECRET_KEY: ""
    STUDIO_RSA_PRIVATE_KEY: ""

  postgres:
    passwordKey: "postgres-password"
  redis:
    passwordKey: "redis-password"


#Read Secrets from Postgres Secrets
secretsPGRef:
  PG_PSWD: "postgres-password"
  PG_ADMIN_PSWD: "postgres-password"

#Read Secrets from Redis Instance Secrets
secretsREDISRef:
  REDIS_PSWD: "redis-password"

image:
  repository: registry.gitlab.com/one37id/registry/solitaire/staging
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: [{"name": "one37secrets-repo-secret"}]

## @param extraVolumes Optionally specify extra list of additional volumes for PhpMyAdmin pods
##
extraVolumes:
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for PhpMyAdmin container(s)
##
extraVolumeMounts:


resources:
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ## limits:
  ##   cpu: 100m
  ##   memory: 128Mi
  limits: {}
  ## requests:
  ##   cpu: 100m
  ##   memory: 128Mi
  requests: {}

pvc:
  enabled: false
  name: "bcagent-pvc"
  accessModes:
    - ReadWriteOnce
  storageClassName: "default"
  size: "1Gi"


nodeSelector: {}

tolerations:

affinity: {}

# Supported values: redis, rabbitmq
replicaQueHandler:
  enabled: false
  handler: redis

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}


podSecurityContext: {}
  # enabled: false
  # fsGroup: 1001
  # fsGroupChangePolicy: "OnRootMismatch"

containerSecurityContext: {}
  # runAsUser: 1001
  # runAsNonRoot: true
  # fsGroupChangePolicy: "OnRootMismatch"

updateStrategy:
#   ## StrategyType
#   ## Can be set to RollingUpdate or OnDelete
#   ##
  type: "OnDelete"