apiVersion: v2
name: one37id-privatestudioapiVersion
type: application
description: A Kubernetes Helm chart for the One37 Private Studio Agent Manager
home: https://one37id.com
icon: https://www.one37id.com/images/connector.svg
annotations:
  category: Infrastructure
  licenses: Apache-2.0
keywords:
  - businessconnector
  - ssi
  - aries
  - agent
  - one37id
  - one37
  - one37id.com
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "1.2.2309.1301"
version: 2.2309.1501
