{{- $fullName := include "one37id-ibm-agent-db.fullname" . -}}
{{- $postgresSecretName := printf "%s" .Values.secrets.postgresSecretName | trunc 63 | trimSuffix "-" -}}
{{- $redisSecretName := printf "%s" .Values.secrets.redisSecretName | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "one37id-ibm-agent-db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "one37id-ibm-agent-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "one37id-ibm-agent-db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "one37id-ibm-agent-db.serviceAccountName" . }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ $fullName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          envFrom:
          - configMapRef:
              name: {{ $fullName }}
          env:
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.secrets.create }}
            {{- range $key, $value := .Values.secrets.app }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $key }}
                  name: {{ $fullName }}
                  optional: false
            {{- end }}
            {{- range $key, $value := .Values.secretsPGRef }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value | quote }}
                  name: {{ $postgresSecretName | quote }}
                  optional: false
            {{- end }}
            {{- range $key, $value := .Values.secretsREDISRef }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value | quote }}
                  name: {{ $redisSecretName | quote }}
                  optional: false
            {{- end }}
          {{- end }}

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-public
              containerPort: {{ .Values.service.publicPort }}
              protocol: TCP
            {{- if .Values.service.twoPortMode }}
            - name: http-admin
              containerPort: {{ .Values.service.adminPort }}
              protocol: TCP
            {{- end }}
          {{- if .Values.liveCheck }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}