
{{- $fullName := include "one37id-ibm-agent-db.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName}}-{{ .Values.resourceVolume.name }}
spec:
  accessModes:
{{ toYaml .Values.resourceVolume.accessModes | indent 4 }}
  storageClassName: {{ .Values.resourceVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.resourceVolume.size }}

