{{- $fullName := include "one37id-mediator.fullname" . -}}
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace.name | quote  }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.app }}
  {{ $key }}: {{ $value | b64enc}}
  {{- end }}
{{- end }}